#!/usr/bin/env ruby

require("fileutils")

# Load Layout
puts("Loading layout")
layout_top, layout_bottom = File.read("src/_layout.html").split("__CONTENT__")



# Get list of pages to generate
puts("Loading pages to generate")
Dir.chdir("src/pages")
pages = Dir["*.html"]
puts("Generating the following pages: #{pages}")



# Construct each page
content = {}

warning = "<!-- This file is autogenerated from the src directory, please do not edit it manually -->"

pages.each do |page_name|
  puts("Assembling #{page_name}")
  page_content = File.read(page_name)

  assembled_content = [warning, layout_top, page_content, layout_bottom].join("\n")

  content[page_name] = assembled_content
  puts("Finshed assembling #{page_name}")
end



# Write out page content
Dir.chdir("../../")
puts("Deleting old content")
FileUtils.rm(Dir["*.html"])
puts("Writing generated content")

content.each do |page_name, page_content|
  puts("Writing #{page_name}")
  File.open(page_name, "w") {|f| f.write(page_content) }
  puts("Finished writing #{page_name}")
end

puts("Finished generating content")
